name: CI

on:
  push:

    branches: 
    - '*'
    tags:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Get hash
      shell: cmd
      working-directory: ./
      run: echo %GITHUB_SHA% > hash.inc

    - name: Compile TS
      run: npm run compileTs --if-present

    - name: Prepare files
      run: npm run prepFiles --if-present

    - name: Run nw-builder
      run: npm run build-main --if-present

    - name: Upload windows binaries
      uses: actions/upload-artifact@v3
      with:
        name: R3_WSP_WIN64
        path: ./Build/r3-water-sample-puzzle/win64/